# Generated by Django 6.0.6 on 2026-07-07 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Total vehicle capacity, if known.', null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='current_occupancy',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
