# Generated by Django 6.0.6 on 2026-07-07 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_zone_capacity_zone_current_occupancy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslot',
            name='manual_override_at',
            field=models.DateTimeField(blank=True, help_text='Last time a human manually set this status. Conflicting sensor reports are deferred for MANUAL_OVERRIDE_GRACE_MINUTES after this.', null=True),
        ),
        migrations.CreateModel(
            name='SlotStatusChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('sensor', 'Sensor'), ('manual', 'Manual')], max_length=10)),
                ('device_id', models.CharField(blank=True, help_text='Set when source is sensor.', max_length=64)),
                ('previous_status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved')], max_length=20)),
                ('attempted_status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved')], max_length=20)),
                ('applied', models.BooleanField(default=True, help_text='False means rejected due to an active manual override.')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, help_text='Set when source is manual.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_change_logs', to='parking.parkingslot')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
