# Generated by Django 6.0.6 on 2026-08-21 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking', '0003_parkingslot_manual_override_at_slotstatuschangelog'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_number', models.CharField(blank=True, help_text='Assigned on approval, e.g. ATU-P-2026-0001.', max_length=20, null=True, unique=True)),
                ('permit_type', models.CharField(choices=[('student', 'Student — semester'), ('staff', 'Staff — academic year'), ('visitor', 'Visitor — short stay'), ('contractor', 'Contractor — project duration')], default='student', max_length=20)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('active', 'Active'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_paid', models.BooleanField(default=False)),
                ('applicant_note', models.CharField(blank=True, help_text='Anything staff should know.', max_length=255)),
                ('document', models.FileField(blank=True, help_text='Supporting document — student ID, appointment letter, etc.', upload_to='permits/%Y/%m/')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, help_text='Reason shown to the applicant.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permits', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_permits', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permits', to='vehicles.vehicle')),
                ('zone', models.ForeignKey(blank=True, help_text='Leave blank for a permit valid in any zone.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permits', to='parking.zone')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='permits_per_status_6c419b_idx'), models.Index(fields=['valid_from', 'valid_until'], name='permits_per_valid_f_cc48af_idx')],
            },
        ),
    ]
