# Generated by Django 6.0.6 on 2026-07-06 20:12

import sensors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='Identifier printed on/flashed to the device, e.g. "ESP32-A1B2C3".', max_length=64, unique=True)),
                ('api_key', models.CharField(default=sensors.models.generate_api_key, editable=False, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
