# Generated by Django 6.0.6 on 2026-07-06 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordevice',
            name='device_type',
            field=models.CharField(choices=[('slot_sensor', 'Slot Sensor'), ('gate_sensor', 'Gate Sensor')], default='slot_sensor', max_length=20),
        ),
        migrations.AddField(
            model_name='sensordevice',
            name='slot',
            field=models.OneToOneField(blank=True, help_text='Required for slot sensors.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensor_device', to='parking.parkingslot'),
        ),
        migrations.AddField(
            model_name='sensordevice',
            name='zone',
            field=models.ForeignKey(blank=True, help_text='Required for gate sensors (a zone may have more than one, e.g. entry + exit).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_sensors', to='parking.zone'),
        ),
    ]
