# Generated by Django 6.0.6 on 2026-07-07 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_zone_capacity_zone_current_occupancy'),
        ('sensors', '0002_sensordevice_device_type_sensordevice_slot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit')], max_length=10)),
                ('plate_number', models.CharField(blank=True, max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_events', to='sensors.sensordevice')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_events', to='parking.zone')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
